### PR TITLE
Define the stage in an `.env` file.

### PR DESCRIPTION
**Pull request by atykhonov**
For a deployment to `test` environment we can use `--env` parameter,
e.g.:

```
sls deploy --env test
```

so no needs to specify `-s` paramater for stage (which doesn't work
btw for a deployment to test environment).

### CODE REVIEW

**Comment by olegtaranenko** [comment]
Please add comment on what other among dev can be assigned to the STAGE variable

**Comment by atykhonov** [comment]
Any value can be assigned to the variable (accordingly to the documentation of `serverless-dotenv-plugin`). I use `test`, i.e. `sls deploy --env test`, it could be `staging` instead. You need to have configured `.env.{STAGE}` file. If you don't have it any other value (rather then default) is useless.

**Comment by olegtaranenko** [comment]
Please add this snippet to the README.md, with link to the serverless plugin documentation

**Comment by atykhonov** [comment]
Neither the snippet nor the link to the documentation doesn't relate to the issue which I fixed here. IMHO what you're asking goes beyond the topic of the issue.

**Pull request merged**
