### PR TITLE
Link a configurable set of default stakeholders to a Jira issue.

### PR DESCRIPTION
**Pull request by atykhonov**

### CODE REVIEW

**Comment by olegtaranenko** [comment]
Please provide info, how to tune up JIRA instance, which should conform to working Glasswall JIRA one

**Comment by olegtaranenko** [comment]
The branch meanwhile got a conflictable state. Need to rebase it

**Comment by atykhonov** [comment]
@olegtaranenko please review.

**Comment by olegtaranenko** [comment]
After merging prev PR current one got conflicted. please fix it

**Comment by atykhonov** [comment]
@olegtaranenko fixed.

**Comment by atykhonov** [comment]
@olegtaranenko please review.

**Comment by olegtaranenko** [comment]
not against to merging

**Pull request merged**
